//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDSL_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Club
    {
        public string clubCode { get; set; }
        public string clubName { get; set; }
        public string contactName { get; set; }
        public string contactSurname { get; set; }
        public string Gender { get; set; }
        public string AddressLine1 { get; set; }
        public Nullable<int> Postcode { get; set; }
        public string State { get; set; }
        public string Suburb { get; set; }
        public string homePhone { get; set; }
        public Nullable<int> firstRegistered { get; set; }
    }
}
