//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDSL_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public string gameCode { get; set; }
        public string homeTeam { get; set; }
        public string awayTeam { get; set; }
        public Nullable<int> homeGoals { get; set; }
        public Nullable<int> awayGoals { get; set; }
        public Nullable<int> gameTime { get; set; }
    }
}
