//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDSL_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class league
    {
        public string administrator { get; set; }
        public string email { get; set; }
        public string leagueAddress { get; set; }
        public string leagueName { get; set; }
        public Nullable<int> phoneNumber { get; set; }
        public string postalAddress { get; set; }
        public string president { get; set; }
        public string website { get; set; }
    }
}
