//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDSL_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public string clubCode { get; set; }
        public string firstName { get; set; }
        public string Surname { get; set; }
        public string Gender { get; set; }
        public string addressLine1 { get; set; }
        public string postCode { get; set; }
        public string State { get; set; }
        public string Suburb { get; set; }
        public string homePhone { get; set; }
        public string Age { get; set; }
        public string birthDate { get; set; }
        public string firstRegistered { get; set; }
        public string teamRank { get; set; }
        public int playerCode { get; set; }
    }
}
