//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDSL_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Season
    {
        public int seasonCode { get; set; }
        public Nullable<int> seasonYear { get; set; }
        public Nullable<int> startDate { get; set; }
        public Nullable<int> numRounds { get; set; }
        public string nonPlayWeeks { get; set; }
        public Nullable<int> endDate { get; set; }
    }
}
